# Generated by Django 4.2.2 on 2023-06-26 13:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoParalelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscripcion', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiantes.cursoparalelo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Niveles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('P', 'Primaria'), ('S', 'Secundaria')], default='P', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Paralelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=50)),
                ('nota', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('aprobacion', models.CharField(choices=[('A', 'Aprobado'), ('R', 'Reprobado')], default='R', max_length=2)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiantes.estudiantes')),
            ],
        ),
        migrations.AddField(
            model_name='cursoparalelo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiantes.cursos'),
        ),
        migrations.AddField(
            model_name='cursoparalelo',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiantes.niveles'),
        ),
        migrations.AddField(
            model_name='cursoparalelo',
            name='paralelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiantes.paralelos'),
        ),
    ]
